#
# Build stage
#
FROM maven:3.9.6-eclipse-temurin-17-alpine@sha256:740d326713d9d56b69a82e49988cd6266b5329e046681c44790b4e0ae2360b56 AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM eclipse-temurin:17-jdk-alpine@sha256:0e6e494ac4da6509a038b7689250bc7ea68beaf8a5efbca5ed7c8692457b283c

# Add the jar file to the container
COPY --from=build /home/app/target/my-playground-api.jar /usr/local/lib/app.jar

# Add a user to run our application so that it doesn't need to run as root
RUN addgroup -S usergroup && adduser -S user -G usergroup

# Set the user to run our application
USER user

# Expose the port our application will run on
EXPOSE 8080

ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar"]